name: vulnsrc
channels:
  - defaults
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - expat=2.6.3
  - fire=0.6.0
  - idna=3.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - loguru=0.5.3
  - ncurses=6.4
  - openssl=3.3.2
  - pip=24.2
  - prettytable=3.5.0
  - pysocks=1.7.1
  - python=3.12.5
  - python-dotenv=0.21.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - termcolor=2.4.0
  - tk=8.6.14
  - tqdm=4.66.5
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - psycopg2-binary==2.9.9
